{
  "hash": "c46d118593140d3c33a3ff16dfb854e1",
  "result": {
    "markdown": "---\ntitle: \"Himalayan Expeditions\"\nauthor: \"\"\ndate: \"2020-10-20\"\ndescription: \"Visualizing a #TidyTuesday-featured dataset on Himalayan expeditions, with a focus on climber nationalities.\"\ncategories: [ \"Tidy Tuesday\", R ]\nimage: \"himalayan-thumbnail.png\"\nimage-alt: \"\"\neditor_options: \n  chunk_output_type: console\n---\n\n<figure>\n<img src=\"./himalayan-featured.png\" alt=\"Stacked bar chart showing frequency of trips taken by seasons over the decades\" width=\"650\">\n<figcaption>See full chart below.</figcaption>\n</figure>\n\n\n::: {.callout-note collapse=\"false\"}\n## What is #TidyTuesday?\n\n[Tidy Tuesday](https://github.com/rfordatascience/tidytuesday) is a weekly project that provides a dataset for R users to explore and visualize. On September 22, 2020, it [featured data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-09-22/readme.md) from [The Himalayan Database](https://www.himalayandatabase.com/), which contains information on expeditions from 1905 through spring 2019 (the online database itself goes up to spring 2021) that scaled more than 465 major peaks in the Nepal Himalayas. \n:::\n\nAccording to the Himalayan Database:\n\n> The database is based on the expedition archives of Elizabeth Hawley, a longtime journalist based in Kathmandu, and it is supplemented by information gathered from books, alpine journals and correspondence with Himalayan climbers.  \n> (...)  \n> Each expedition record contains detailed information including dates, routes, camps, use of supplemental oxygen, successes, deaths and accidents.  \n>  \n> Each expedition record contains biographical information for all members listed on the permit as well as for hired members (e.g., Sherpas) for which there are significant events such as a summit success, death, accident or rescue.\n\nThis post shows the exploration process of two of the datasets, and uses the `tidyverse` set of R packages for data wrangling and visualization.\n\nStarting out with an overview of the records:\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(expeditions)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 10,364\nColumns: 16\n$ expedition_id      <chr> \"ANN260101\", \"ANN269301\", \"ANN273101\", \"ANN278301\",…\n$ peak_id            <chr> \"ANN2\", \"ANN2\", \"ANN2\", \"ANN2\", \"ANN2\", \"ANN2\", \"AN…\n$ peak_name          <chr> \"Annapurna II\", \"Annapurna II\", \"Annapurna II\", \"An…\n$ year               <dbl> 1960, 1969, 1973, 1978, 1979, 1980, 1980, 1981, 198…\n$ season             <chr> \"Spring\", \"Autumn\", \"Spring\", \"Autumn\", \"Autumn\", \"…\n$ basecamp_date      <date> 1960-03-15, 1969-09-25, 1973-03-16, 1978-09-08, NA…\n$ highpoint_date     <date> 1960-05-17, 1969-10-22, 1973-05-06, 1978-10-02, 19…\n$ termination_date   <date> NA, 1969-10-26, NA, 1978-10-05, 1979-10-20, 1980-0…\n$ termination_reason <chr> \"Success (main peak)\", \"Success (main peak)\", \"Succ…\n$ highpoint_metres   <dbl> 7937, 7937, 7937, 7000, 7160, 7000, 7250, 6400, 740…\n$ members            <dbl> 10, 10, 6, 2, 3, 6, 7, 19, 9, 5, 5, 5, 6, 4, 3, 4, …\n$ member_deaths      <dbl> 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, …\n$ hired_staff        <dbl> 9, 0, 8, 0, 0, 2, 2, 0, 3, 0, 0, 3, 4, 2, 0, 2, 5, …\n$ hired_staff_deaths <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ oxygen_used        <lgl> TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FAL…\n$ trekking_agency    <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, \"Kunga\"…\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(members)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 76,519\nColumns: 21\n$ expedition_id        <chr> \"AMAD78301\", \"AMAD78301\", \"AMAD78301\", \"AMAD78301…\n$ member_id            <chr> \"AMAD78301-01\", \"AMAD78301-02\", \"AMAD78301-03\", \"…\n$ peak_id              <chr> \"AMAD\", \"AMAD\", \"AMAD\", \"AMAD\", \"AMAD\", \"AMAD\", \"…\n$ peak_name            <chr> \"Ama Dablam\", \"Ama Dablam\", \"Ama Dablam\", \"Ama Da…\n$ year                 <dbl> 1978, 1978, 1978, 1978, 1978, 1978, 1978, 1978, 1…\n$ season               <chr> \"Autumn\", \"Autumn\", \"Autumn\", \"Autumn\", \"Autumn\",…\n$ sex                  <chr> \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\",…\n$ age                  <dbl> 40, 41, 27, 40, 34, 25, 41, 29, 35, 37, 23, 44, 2…\n$ citizenship          <chr> \"France\", \"France\", \"France\", \"France\", \"France\",…\n$ expedition_role      <chr> \"Leader\", \"Deputy Leader\", \"Climber\", \"Exp Doctor…\n$ hired                <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …\n$ highpoint_metres     <dbl> NA, 6000, NA, 6000, NA, 6000, 6000, 6000, NA, 681…\n$ success              <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …\n$ solo                 <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …\n$ oxygen_used          <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …\n$ died                 <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …\n$ death_cause          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ death_height_metres  <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ injured              <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …\n$ injury_type          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ injury_height_metres <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n```\n:::\n:::\n\n\nGiven that each record is of a member of an expedition, how many different expeditions occurred, according to the datasets?\n\nFor `expeditions`, will each row be a unique expedition?\n\n::: {.cell}\n\n```{.r .cell-code}\nexpeditions %>% count(expedition_id, sort=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10,363 × 2\n   expedition_id     n\n   <chr>         <int>\n 1 KANG10101         2\n 2 ACHN15301         1\n 3 ACHN15302         1\n 4 ACHN18301         1\n 5 AMAD00101         1\n 6 AMAD00102         1\n 7 AMAD00103         1\n 8 AMAD00104         1\n 9 AMAD00105         1\n10 AMAD00106         1\n# … with 10,353 more rows\n```\n:::\n:::\n\nSince `KANG10101` appears twice, how do those rows appear?\n\n::: {.cell}\n\n```{.r .cell-code}\nexpeditions %>%\n  filter(expedition_id==\"KANG10101\") %>%\n  datatable(options = list(dom = 't', scrollX = TRUE))\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-8d0fe7d584c8dc31de8b\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-8d0fe7d584c8dc31de8b\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\"],[\"KANG10101\",\"KANG10101\"],[\"KANG\",\"KANG\"],[\"Kangchenjunga\",\"Kangchenjunga\"],[1910,2010],[\"Spring\",\"Spring\"],[null,\"2010-03-24\"],[null,\"2010-04-29\"],[null,\"2010-05-01\"],[\"Did not attempt climb\",\"Success (main peak)\"],[null,8586],[1,4],[0,0],[0,2],[0,0],[false,true],[null,\"Windhorse Trekking\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>expedition_id<\\/th>\\n      <th>peak_id<\\/th>\\n      <th>peak_name<\\/th>\\n      <th>year<\\/th>\\n      <th>season<\\/th>\\n      <th>basecamp_date<\\/th>\\n      <th>highpoint_date<\\/th>\\n      <th>termination_date<\\/th>\\n      <th>termination_reason<\\/th>\\n      <th>highpoint_metres<\\/th>\\n      <th>members<\\/th>\\n      <th>member_deaths<\\/th>\\n      <th>hired_staff<\\/th>\\n      <th>hired_staff_deaths<\\/th>\\n      <th>oxygen_used<\\/th>\\n      <th>trekking_agency<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[4,10,11,12,13,14]},{\"orderable\":false,\"targets\":0}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nThey are indeed two different expeditions, a century apart. How many other expeditions have missing values? I'll use a function from the `[naniar](https://naniar.njtierney.com/)` package, which shows the number and percentage of missing values for each variable.\n\n::: {.cell}\n\n```{.r .cell-code}\nnaniar::miss_var_summary(expeditions)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 16 × 3\n   variable           n_miss pct_miss\n   <chr>               <int>    <dbl>\n 1 termination_date     2380 23.0    \n 2 trekking_agency      1580 15.2    \n 3 basecamp_date        1095 10.6    \n 4 highpoint_date        650  6.27   \n 5 highpoint_metres      414  3.99   \n 6 peak_name               1  0.00965\n 7 expedition_id           0  0      \n 8 peak_id                 0  0      \n 9 year                    0  0      \n10 season                  0  0      \n11 termination_reason      0  0      \n12 members                 0  0      \n13 member_deaths           0  0      \n14 hired_staff             0  0      \n15 hired_staff_deaths      0  0      \n16 oxygen_used             0  0      \n```\n:::\n:::\n\nFor expeditions without a basecamp date, were the reasons?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexpeditions %>%\n  filter(is.na(basecamp_date)) %>%\n  count(termination_reason)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 15 × 2\n   termination_reason                                                          n\n   <chr>                                                                   <int>\n 1 Accident (death or serious injury)                                         39\n 2 Attempt rumoured                                                           12\n 3 Bad conditions (deep snow, avalanching, falling ice, or rock)              47\n 4 Bad weather (storms, high winds)                                           54\n 5 Did not attempt climb                                                     137\n 6 Did not reach base camp                                                    59\n 7 Illness, AMS, exhaustion, or frostbite                                     26\n 8 Lack (or loss) of supplies or equipment                                     7\n 9 Lack of time                                                                1\n10 Other                                                                     109\n11 Route technically too difficult, lack of experience, strength, or moti…    41\n12 Success (claimed)                                                           6\n13 Success (main peak)                                                       446\n14 Success (subpeak)                                                          20\n15 Unknown                                                                    91\n```\n:::\n:::\n\nThough these trips did not happen in the end, they're still considered expeditions and `KANG10101` as two distinct expeditions. How does this ID appear in the `members` dataset? Are the two years present there too? (Yes.)\n\n::: {.cell}\n\n```{.r .cell-code}\nmembers %>%\n  filter(expedition_id==\"KANG10101\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 7 × 21\n  exped…¹ membe…² peak_id peak_…³  year season sex     age citiz…⁴ exped…⁵ hired\n  <chr>   <chr>   <chr>   <chr>   <dbl> <chr>  <chr> <dbl> <chr>   <chr>   <lgl>\n1 KANG10… KANG10… KANG    Kangch…  1910 Spring M        41 UK      Leader  FALSE\n2 KANG10… KANG10… KANG    Kangch…  2010 Spring M        53 S Korea Leader  FALSE\n3 KANG10… KANG10… KANG    Kangch…  2010 Spring M        40 S Korea Climber FALSE\n4 KANG10… KANG10… KANG    Kangch…  2010 Spring M        47 S Korea Climber FALSE\n5 KANG10… KANG10… KANG    Kangch…  2010 Spring M        30 S Korea Climber FALSE\n6 KANG10… KANG10… KANG    Kangch…  2010 Spring M        27 Nepal   H-A Wo… TRUE \n7 KANG10… KANG10… KANG    Kangch…  2010 Spring M        39 Nepal   H-A Wo… TRUE \n# … with 10 more variables: highpoint_metres <dbl>, success <lgl>, solo <lgl>,\n#   oxygen_used <lgl>, died <lgl>, death_cause <chr>,\n#   death_height_metres <dbl>, injured <lgl>, injury_type <chr>,\n#   injury_height_metres <dbl>, and abbreviated variable names ¹​expedition_id,\n#   ²​member_id, ³​peak_name, ⁴​citizenship, ⁵​expedition_role\n```\n:::\n:::\n\n\nIs every expedition listed in `expeditions` also in `members`? I'll use the `setdiff()` function to see if any IDs from `expeditions` are not found in `members`.\n\n::: {.cell}\n\n```{.r .cell-code}\nsetdiff(expeditions$expedition_id, members$expedition_id)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"ANN186305\" \"CHEO87301\" \"DHA149001\" \"EVER68101\" \"EVER79102\" \"GAUR73301\"\n [7] \"KGUR65101\" \"MAKA34101\" \"MANA70301\" \"YALU65101\" \"YALU67101\" \"EVER65102\"\n[13] \"EVER19185\"\n```\n:::\n:::\n\n\nThere are 13. Any particular commonalities between those expeditions?\n\n::: {.cell}\n\n```{.r .cell-code}\nexpeditions_only <- setdiff(expeditions$expedition_id, members$expedition_id) # creates a character string\n\nexpeditions %>% \n  filter(expedition_id %in% expeditions_only)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 13 × 16\n   exped…¹ peak_id peak_…²  year season basecamp…³ highpoin…⁴ terminat…⁵ termi…⁶\n   <chr>   <chr>   <chr>   <dbl> <chr>  <date>     <date>     <date>     <chr>  \n 1 ANN186… ANN1    Annapu…  1986 Autumn NA         NA         NA         Did no…\n 2 CHEO87… CHEO    Cheo H…  1987 Autumn NA         NA         NA         Did no…\n 3 DHA149… DHA1    Dhaula…  1949 Unkno… NA         NA         NA         Attemp…\n 4 EVER68… EVER    Everest  1968 Spring NA         NA         NA         Attemp…\n 5 EVER79… EVER    Everest  1979 Spring NA         NA         NA         Did no…\n 6 GAUR73… GAUR    Gauris…  1973 Autumn NA         NA         NA         Did no…\n 7 KGUR65… KGUR    Kang G…  1965 Spring NA         NA         NA         Attemp…\n 8 MAKA34… MAKA    Makalu   1934 Spring NA         NA         NA         Did no…\n 9 MANA70… MANA    Manaslu  1970 Autumn NA         NA         NA         Did no…\n10 YALU65… YALU    Yalung…  1965 Spring NA         NA         NA         Did no…\n11 YALU67… YALU    Yalung…  1967 Spring NA         NA         NA         Did no…\n12 EVER65… EVER    Everest  1965 Spring NA         NA         NA         Attemp…\n13 EVER19… EVER    Everest  2019 Spring NA         2019-05-22 NA         Succes…\n# … with 7 more variables: highpoint_metres <dbl>, members <dbl>,\n#   member_deaths <dbl>, hired_staff <dbl>, hired_staff_deaths <dbl>,\n#   oxygen_used <lgl>, trekking_agency <chr>, and abbreviated variable names\n#   ¹​expedition_id, ²​peak_name, ³​basecamp_date, ⁴​highpoint_date,\n#   ⁵​termination_date, ⁶​termination_reason\n```\n:::\n\n```{.r .cell-code}\n# ANN186305\n```\n:::\n\nThe expeditions range from 1924 through the 1980s, and one from 2019. That one from 2019 is the only successful trip (termination date not available possibly due to it occurring after the end date of the dataset timeframe) while the rest were either rumored attempts or climbs that were not attempted, with one expedition not reaching the base camp.\n\nAny IDs found in `members` but not in `expeditions`? (No)\n\n::: {.cell}\n\n```{.r .cell-code}\nsetdiff(members$expedition_id, expeditions$expedition_id)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncharacter(0)\n```\n:::\n:::\n\n\nTherefore, the number of *unique* expedition IDs in the `members` data (which has a total 76,519 rows) should be 13 less than number of *unique* observations in the `expeditions` data (which, as found earlier, has 10,364 with one \"duplicate\" ID).\n\n::: {.cell}\n\n```{.r .cell-code}\nmembers %>%\n  count(expedition_id, sort=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10,350 × 2\n   expedition_id     n\n   <chr>         <int>\n 1 EVER88101        99\n 2 HIML13308        90\n 3 EVER15106        79\n 4 EVER08101        76\n 5 MANA16304        71\n 6 EVER18185        69\n 7 EVER73101        68\n 8 EVER13181        65\n 9 EVER19117        65\n10 EVER17110        64\n# … with 10,340 more rows\n```\n:::\n:::\n\nGoing forward, I'll focus on the `year`, `season`, `age`, `citizenship` and `gender` variables in creating the visualizations. The `expedition role` specifies the titles of each individuals, with the most commons ones being `climber`, `H-A worker`, `leader`, `expedition doctor` and `deputy leader`. In this post all individuals will be referred to as `climbers`.\n\n### Seasons and decades\n\nDo the expeditions tend to occur during certain seasons and has that been the case throughout the decades?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexpeditions %>%\n  mutate(decade = case_when(\n    year >= \"1900\" & year <= \"1909\" ~ \"1900-'09\",\n    year >= \"1910\" & year <= \"1919\" ~ \"'10-'19\",\n    year >= \"1920\" & year <= \"1929\" ~ \"'20-'29\",\n    year >= \"1930\" & year <= \"1939\" ~ \"'30-'39\",\n    year >= \"1940\" & year <= \"1949\" ~ \"'40-'49\",\n    year >= \"1950\" & year <= \"1959\" ~ \"'50-'59\",\n    year >= \"1960\" & year <= \"1969\" ~ \"'60-'69\",\n    year >= \"1970\" & year <= \"1979\" ~ \"'70-'79\",\n    year >= \"1980\" & year <= \"1989\" ~ \"'80-'89\",\n    year >= \"1990\" & year <= \"1999\" ~ \"'90-'99\",\n    year >= \"2000\" & year <= \"2009\" ~ \"2000-'09\",\n    year >= \"2010\" & year <= \"2019\" ~ \" '10-'19 \",\n    TRUE ~ \"Unknown\")) %>%\n  mutate(year = lubridate::ymd(year, truncated = 2L)) %>%\n  filter(season != \"Unknown\") %>%\n  mutate(season = factor(season, levels=c(\"Winter\", \"Spring\", \"Summer\", \"Autumn\"))) %>%\n  mutate(decade = factor(decade, levels=c(\"1900-'09\", \"'10-'19\", \"'20-'29\", \"'30-'39\", \"'40-'49\", \"'50-'59\", \"'60-'69\", \"'70-'79\", \"'80-'89\", \"'90-'99\", \"2000-'09\", \" '10-'19 \"))) %>%\n  ggplot(aes(decade, ..count.., fill = season)) +\n    geom_bar(width = 0.7, alpha = 0.9) +\n    scale_y_continuous(expand = c(0,0), labels = scales::comma_format()) +\n    scale_fill_manual(values=c(\"#4e89ae\", \"#fe7171\", \"#f0a500\", \"#7ea04d\")) +\n    annotate(\"text\", label = \"Winter expeditions\\npeaked in the '80s\",\n             x = 5, y = 1150, size = 3.5, color = \"#4e89ae\", family=\"Commissioner\", hjust = 0) +\n    geom_segment(aes(x = 7.5, y = 1140, xend = 8.4, yend = 1140),\n                 size = 0.45, color = \"#4e89ae\",\n                 arrow = arrow(length = unit(1.5, \"mm\"))) +\n    annotate(\"text\", label = \"In the '80s and '90s,\\nautumn expeditions\\noutnumbered those\\nin the spring\", \n             x = 7.5, y = 2200, size = 3.5, color = \"#7ea04d\", family=\"Commissioner\", hjust = 0) +\n    theme_linedraw() +\n    theme(plot.title = element_text(face=\"bold\"),\n                   plot.title.position = \"plot\",\n                   plot.background = element_rect(fill = \"#fff7f5\", color = NA),\n                   legend.position = \"top\", \n                   legend.justification = \"left\",\n                   legend.direction = \"horizontal\",\n                   legend.background = element_rect(fill = \"#fff7f5\", color = NA),\n                   legend.text = element_text(margin = margin(r = 0.28, unit = 'cm'), size = 10),\n                   legend.box.margin = margin(c(0,0,0,-54)),\n                   text = element_text(family = \"Commissioner\"),\n                   panel.grid.major.x = element_blank(),\n                   panel.grid.minor.x = element_blank()) +\n    labs(x = NULL,\n         y = \"Number of expeditions\",\n         title = \"Slight Seasonal Shifts Over Decades of Expeditions\",\n         subtitle = \"Expeditions span 1905-2019\",\n         fill = NULL,\n         caption = \"Source: #TidyTuesday | Himalayan Database\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nRather than relying solely on eyeballing the seasonal proportions, here are the actual percentages listed in tabular form (using the [DT package](https://rstudio.github.io/DT/)). Now it's clear more spring expeditions occurred in every decade except for the 1980s and 1990s, during which the autumn months dominated.\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DT)\n\nexpeditions %>%\n  mutate(decade = case_when(\n    year >= \"1900\" & year <= \"1909\" ~ \"1900-1909\",\n    year >= \"1910\" & year <= \"1919\" ~ \"1910-1919\",\n    year >= \"1920\" & year <= \"1929\" ~ \"1920-1929\",\n    year >= \"1930\" & year <= \"1939\" ~ \"1930-1939\",\n    year >= \"1940\" & year <= \"1949\" ~ \"1940-1949\",\n    year >= \"1950\" & year <= \"1959\" ~ \"1950-1959\",\n    year >= \"1960\" & year <= \"1969\" ~ \"1960-1969\",\n    year >= \"1970\" & year <= \"1979\" ~ \"1970-1979\",\n    year >= \"1980\" & year <= \"1989\" ~ \"1980-1989\",\n    year >= \"1990\" & year <= \"1999\" ~ \"1990-1999\",\n    year >= \"2000\" & year <= \"2009\" ~ \"2000-2009\",\n    year >= \"2010\" & year <= \"2019\" ~ \"2010-2019 \",\n    TRUE ~ \"Unknown\")) %>%\n  mutate(year = lubridate::ymd(year, truncated = 2L)) %>%\n  filter(season != \"Unknown\") %>%\n  count(decade, season) %>%\n  group_by(decade) %>%\n  mutate(pct = round((n/sum(n)*100), digits=1)) %>%\n  ungroup() %>%\n  select(-n) %>%\n  spread(season, pct) %>% \n  select(Deacde = decade, Winter, Spring, Summer, Autumn) %>%\n  mutate(Winter = replace_na(Winter, \"-\")) %>%\n  mutate(Spring = replace_na(Spring, \"-\")) %>%\n  mutate(Summer = replace_na(Summer, \"-\")) %>%\n  mutate(Autumn = replace_na(Autumn, \"-\")) %>% \n  datatable(options = list(dom = 't',\n                           pageLength = nrow(.)))\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-350d81d973ee4a4455f5\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-350d81d973ee4a4455f5\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\"],[\"1900-1909\",\"1910-1919\",\"1920-1929\",\"1930-1939\",\"1940-1949\",\"1950-1959\",\"1960-1969\",\"1970-1979\",\"1980-1989\",\"1990-1999\",\"2000-2009\",\"2010-2019 \"],[\"-\",\"-\",\"10\",\"-\",\"-\",\"-\",\"0.6\",\"0.6\",\"11.6\",\"4.9\",\"1.8\",\"0.9\"],[\"-\",\"100\",\"60\",\"64.7\",\"71.4\",\"57.7\",\"61.9\",\"52.6\",\"34.1\",\"36.1\",\"49.9\",\"52.1\"],[\"25\",\"-\",\"10\",\"20.6\",\"28.6\",\"6\",\"0.6\",\"-\",\"1.5\",\"1.2\",\"1.1\",\"0.3\"],[\"75\",\"-\",\"20\",\"14.7\",\"-\",\"36.3\",\"36.9\",\"46.8\",\"52.7\",\"57.8\",\"47.2\",\"46.7\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Deacde<\\/th>\\n      <th>Winter<\\/th>\\n      <th>Spring<\\/th>\\n      <th>Summer<\\/th>\\n      <th>Autumn<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":12,\"columnDefs\":[{\"orderable\":false,\"targets\":0}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,12,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nThe rest of the charts focus on the `citizenship` variable which lists the country or countries of origin for the climbers. Only 10 out of the more than 76,500 expeditions do not have a country or countries listed for the climber. The charts do not include individuals with more than one country of citizenship listed.\n\nFirst, I'm creating a custom theme (based on the bar chart above) that I'll use in addition to `theme_linedraw()`.\n\n::: {.cell}\n\n```{.r .cell-code}\ntheme_him <- theme_linedraw() + theme(plot.title = element_text(face=\"bold\"),\n                   plot.title.position = \"plot\",\n                   plot.background = element_rect(fill = \"#fff7f5\", color = NA),\n                   legend.position = \"top\", \n                   legend.justification = \"left\",\n                   legend.direction = \"horizontal\",\n                   legend.background = element_rect(fill = \"#fff7f5\", color = NA),\n                   legend.text = element_text(margin = margin(r = 0.28, unit = 'cm'), size = 10),\n                   legend.box.margin = margin(c(0,0,0,-77)),\n                   text = element_text(family = \"Commissioner\"),\n                   axis.title = element_text(size = 10),\n                   panel.grid.major.y = element_blank(),\n                   panel.grid.minor.y = element_blank())\n```\n:::\n\n\nDo expeditions tend to happen during certain seasons? \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmembers %>%\n  count(citizenship, season, sort=T) %>%\n  group_by(citizenship) %>%\n  filter(sum(n) > 500) %>% # filter by countries with total climbers > 500\n  mutate(n_country = sum(n)) %>%\n  ungroup() %>%\n  mutate(season = factor(season, levels=c(\"Winter\", \"Spring\", \"Summer\", \"Autumn\", \"Unknown\"))) %>%\n  mutate(citizenship = fct_reorder(citizenship, n_country)) %>%\n  ggplot(aes(citizenship, n, fill = season)) +\n    geom_col(position = position_stack(reverse = TRUE)) +\n    scale_y_continuous(expand = c(0,0), labels = scales::comma_format()) +\n    scale_fill_manual(values=c(\"#4e89ae\", \"#fe7171\", \"#f0a500\", \"#7ea04d\", \"#d2d3c9\")) +\n    # Japan\n    annotate(\"text\", label = \"In addition to higher than average winter trips,\\nclimbers with Japanese citizenship make the\\nmost summer trips.\",\n             x = 20.5, y = 8000, size = 3.25, color = \"#f0a500\", family=\"Commissioner\", hjust = 0) +\n    geom_segment(aes(x = 21, y = 7700, xend = 21, yend = 6700),\n                 size = 0.45, color = \"#f0a500\",\n                 arrow = arrow(length = unit(1.5, \"mm\"))) +\n    # France\n    annotate(\"text\", label = \"France has a disproportionately high\\nnumber of autumn expeditions.\",\n             x = 18.65, y = 6100, size = 3.25, color = \"#7ea04d\", family=\"Commissioner\", hjust = 0) +\n    geom_segment(aes(x = 19, y = 5900, xend = 19, yend = 4900),\n                 size = 0.45, color = \"#7ea04d\",\n                 arrow = arrow(length = unit(1.5, \"mm\"))) +\n    # South Korea\n    annotate(\"text\", label = \"South Korea has a notably high number\\n(and proportion) of climbers involved\\nin winter expeditions, followed by fellow\\nAsian countries Japan and Nepal.\",\n             x = 15.95, y = 4500, size = 3.25, color = \"#4e89ae\", family=\"Commissioner\", hjust = 0) +\n    geom_segment(aes(x = 17, y = 4200, xend = 17, yend = 3200),\n                 size = 0.45, color = \"#4e89ae\",\n                 arrow = arrow(length = unit(1.5, \"mm\"))) +\n    # India\n    annotate(\"text\", label = \"India stands out for its unusually\\nhigh proportion of climbers making the \\ntrip in the spring, similar to Russia.\",\n             x = 10.5, y = 3600, size = 3.25, color = \"#fe7171\", family=\"Commissioner\", hjust = 0) +\n    geom_segment(aes(x = 11, y = 3275, xend = 11, yend = 2275),\n                 size = 0.45, color = \"#fe7171\",\n                 arrow = arrow(length = unit(1.5, \"mm\"))) +\n    theme_him +\n    labs(x = NULL,\n         y = \"Number of expeditions\",\n         title = \"Expeditions by Season and Country\",\n         subtitle = \"Includes countries with more than 500 climbers\",\n         fill = NULL,\n         caption = \"Source: #TidyTuesday | Himalayan Database\") +\n    coord_flip()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nWhile the earlier chart showed that overall, more expeditions occurred in the spring, breaking the data down by countries reveals distinctions, as noted above.\n\n### Trips by decades\n\nThe next bar chart visualizes the number of trips per 20-year time frames. While the majority of the countries with at least 500 climbers had the largest proportion of trips occur in 2000-2019, take a look at those that did not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmembers %>%\n  mutate(decade = case_when(\n    year >= \"1900\" & year <= \"1919\" ~ \"1900-1919\",\n    year >= \"1920\" & year <= \"1939\" ~ \"1920-1939\",\n    year >= \"1940\" & year <= \"1959\" ~ \"1940-1959\",\n    year >= \"1960\" & year <= \"1979\" ~ \"1960-1979\",\n    year >= \"1980\" & year <= \"1999\" ~ \"1980-1999\",\n    year >= \"2000\" & year <= \"2019\" ~ \"2000-2019\",\n    TRUE ~ \"NA\")) %>%\n  count(citizenship, decade, sort=T) %>%\n  group_by(citizenship) %>%\n  filter(sum(n) > 500) %>%\n  mutate(n_country = sum(n)) %>%\n  ungroup() %>%\n  mutate(citizenship = fct_reorder(citizenship, n_country)) %>%\n  ggplot(aes(citizenship, n, fill = decade)) +\n    geom_col(position = position_stack(reverse = TRUE)) +\n    scale_y_continuous(expand = c(0,0), labels = scales::comma_format()) +\n    scale_fill_manual(values = PNWColors::pnw_palette(name = \"Sailboat\", n = 6, type = \"discrete\")) +\n    # Japan\n    annotate(\"text\", label = \"An unusually large number of Japanese\\nclimbers made the trek in 1960-1979.\\nJapan also has the distinction of being\\nthe only country here with more trips\\nmade in 1980-1999 than in 2000-2019.\",\n             x = 19.65, y = 8000, size = 3.25, color = \"#f0a500\", family=\"Commissioner\", hjust = 0) +\n    geom_segment(aes(x = 21, y = 7700, xend = 21, yend = 6700),\n                 size = 0.45, color = \"#f0a500\",\n                 arrow = arrow(length = unit(1.5, \"mm\"))) +\n    # South Korea\n    annotate(\"text\", label = \"Along with France, Spain and Switzerland,\\nSouth Korea has a comparable share of\\nclimbers who made the trip in 1980-1999\\nand 2000-2019.\",\n             x = 16, y = 4500, size = 3.25, color = \"#E89C81\", family=\"Commissioner\", hjust = 0) +\n    geom_segment(aes(x = 17, y = 4200, xend = 17, yend = 3200),\n                 size = 0.45, color = \"#E89C81\",\n                 arrow = arrow(length = unit(1.5, \"mm\"))) +\n    # China\n    annotate(\"text\", label = \"China, and Nepal (for very different reasons),\\nhave the largest proportions of trip made\\nin 2000-2019.\",\n             x = 12.3, y = 3750, size = 3.25, color = \"#D2848D\", family=\"Commissioner\", hjust = 0) +\n    geom_segment(aes(x = 13, y = 3500, xend = 13, yend = 2500),\n                 size = 0.45, color = \"#D2848D\",\n                 arrow = arrow(length = unit(1.5, \"mm\"))) +\n    theme_him +\n    labs(x = NULL,\n         y = \"Number of Expeditions\",\n         title = \"Expeditions by Decades and Country\",\n         subtitle = \"Includes countries with more than 500 climbers\",\n         fill = NULL,\n         caption = \"Source: #TidyTuesday | Himalayan Database\") +\n    coord_flip()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\nHere are the specific percentages by decade. About half the trips recorded in the dataset occurred between 2000 and 2019.\n\n::: {.cell}\n\n```{.r .cell-code}\nmembers %>%\n  mutate(decade = case_when(\n    year >= \"1900\" & year <= \"1909\" ~ \"1900-1909\",\n    year >= \"1910\" & year <= \"1919\" ~ \"1910-1919\",\n    year >= \"1920\" & year <= \"1929\" ~ \"1920-1929\",\n    year >= \"1930\" & year <= \"1939\" ~ \"1930-1939\",\n    year >= \"1940\" & year <= \"1949\" ~ \"1940-1949\",\n    year >= \"1950\" & year <= \"1959\" ~ \"1950-1959\",\n    year >= \"1960\" & year <= \"1969\" ~ \"1960-1969\",\n    year >= \"1970\" & year <= \"1979\" ~ \"1970-1979\",\n    year >= \"1980\" & year <= \"1989\" ~ \"1980-1989\",\n    year >= \"1990\" & year <= \"1999\" ~ \"1990-1999\",\n    year >= \"2000\" & year <= \"2009\" ~ \"2000-2009\",\n    year >= \"2010\" & year <= \"2019\" ~ \"2010-2019\",\n    TRUE ~ \"NA\")) %>%\n  count(decade, sort=T) %>%\n  mutate(pct = round(n/sum(n)*100, digit=1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 12 × 3\n   decade        n   pct\n   <chr>     <int> <dbl>\n 1 2010-2019 24832  32.5\n 2 2000-2009 21327  27.9\n 3 1990-1999 13746  18  \n 4 1980-1989 10371  13.6\n 5 1970-1979  3709   4.8\n 6 1960-1969  1161   1.5\n 7 1950-1959   953   1.2\n 8 1930-1939   266   0.3\n 9 1920-1929    70   0.1\n10 1940-1949    68   0.1\n11 1900-1909    13   0  \n12 1910-1919     3   0  \n```\n:::\n:::\n\n\n\n### Age factor\n\nAsian countries continue to divert from the overall trends of the group of countries, particularly in the case of climber age. Missing values, which for the age variable make up about 4.6%, have been excluded from the chart. Unsurprisingly, the 25-34 and 35-44 age groups make up the largest proportions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmembers %>%\n  mutate(age_range = case_when(\n    age <= \"17\" ~ \"Under 18\",\n    age >= \"18\" & age <= \"24\" ~ \"18-24\",\n    age >= \"25\" & age <= \"34\" ~ \"25-34\",\n    age >= \"35\" & age <= \"44\" ~ \"35-44\",\n    age >= \"45\" & age <= \"54\" ~ \"45-54\",\n    age >= \"55\" & age <= \"64\" ~ \"55-64\",\n    age >= \"65\" ~ \"65+\",\n    TRUE ~ \"Unknown\")) %>%\n  filter(age_range != \"Unknown\") %>%\n  count(citizenship, age_range, sort=T) %>%\n  group_by(citizenship) %>%\n  filter(sum(n) > 500) %>%\n  mutate(n_country = sum(n)) %>%\n  ungroup() %>%\n  mutate(age_range = factor(age_range, levels=c(\"Under 18\", \"18-24\", \"25-34\", \"35-44\", \"45-54\", \"55-64\", \"65+\"))) %>%\n  mutate(citizenship = fct_reorder(citizenship, n_country)) %>%\n  ggplot(aes(citizenship, n, fill = age_range)) +\n    geom_col(position = position_stack(reverse = TRUE)) +\n    scale_y_continuous(expand = c(0,0), labels = scales::comma_format()) +\n    paletteer::scale_fill_paletteer_d(\"awtools::a_palette\", direction = 1) +\n    # Japan\n    annotate(\"text\", label = \"Japanese make up the majority\\nof climbers 65+\",\n             x = 20.7, y = 7800, size = 3.25, color = \"#E74A60\", family=\"Commissioner\", hjust = 0) +\n    geom_segment(aes(x = 21, y = 7500, xend = 21, yend = 6500),\n                 size = 0.45, color = \"#E74A60\",\n                 arrow = arrow(length = unit(1.5, \"mm\"))) +\n    # India\n    annotate(\"text\", label = \"India, along with fellow Asian countries\\nChina, South Korea, Japan and Nepal,\\nhave a noticeably higher proportion of\\nclimbers 18-24 years of age\",\n             x = 9.9, y = 3300, size = 3.25, color = \"#2B363C\", family=\"Commissioner\", hjust = 0) +\n    geom_segment(aes(x = 11, y = 3000, xend = 11, yend = 2000),\n                 size = 0.45, color = \"#2B363C\",\n                 arrow = arrow(length = unit(1.5, \"mm\"))) +\n    theme_him +\n    labs(y = \"Number of expeditions\",\n         x = NULL,\n         title = \"Expeditions by Age Group and Country\",\n         subtitle = \"Includes countries with more than 500 climbers\",\n         fill = NULL,\n         caption = \"Source: #TidyTuesday | Himalayan Database\") +\n    coord_flip()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n<hr />\nGiven the age distinction with Japan, out of all of the country's climbers, how many, percentage-wise, are older than 65? 6% (To put the number in perspective, the table includes countries with percentages > 1 and number of expeditions > 9. )\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmembers %>%\n  mutate(age_range = case_when(\n    age <= \"17\" ~ \"Under 18\",\n    age >= \"18\" & age <= \"24\" ~ \"18-24\",\n    age >= \"25\" & age <= \"34\" ~ \"25-34\",\n    age >= \"35\" & age <= \"44\" ~ \"35-44\",\n    age >= \"45\" & age <= \"54\" ~ \"45-54\",\n    age >= \"55\" & age <= \"64\" ~ \"55-64\",\n    age >= \"65\" ~ \"65+\",\n    TRUE ~ \"Unknown\")) %>%\n  filter(age_range != \"Unknown\") %>%\n  count(citizenship, age_range, sort=T) %>%\n  group_by(citizenship) %>%\n  mutate(pct = round(n/sum(n)*100)) %>%\n  ungroup() %>%\n  filter(age_range == \"65+\" & pct > 1 & n > 9) %>%\n  arrange(desc(pct)) %>%\n  select(-age_range)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  citizenship     n   pct\n  <chr>       <int> <dbl>\n1 Japan         342     6\n2 USA           110     2\n3 France         69     2\n4 Germany        48     2\n5 Russia         23     2\n6 Slovenia       11     2\n```\n:::\n:::\n\n<hr />\nFramed another way, what percentage of all climbers older than 65 are Japanese? 38.7% (The table includes the countries with the 10 highest percentages.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmembers %>%\n  mutate(age_range = case_when(\n    age <= \"17\" ~ \"Under 18\",\n    age >= \"18\" & age <= \"24\" ~ \"18-24\",\n    age >= \"25\" & age <= \"34\" ~ \"25-34\",\n    age >= \"35\" & age <= \"44\" ~ \"35-44\",\n    age >= \"45\" & age <= \"54\" ~ \"45-54\",\n    age >= \"55\" & age <= \"64\" ~ \"55-64\",\n    age >= \"65\" ~ \"65+\",\n    TRUE ~ \"Unknown\")) %>%\n  filter(age_range != \"Unknown\") %>%\n  count(citizenship, age_range, sort=T) %>%\n  filter(age_range == \"65+\") %>%\n  mutate(pct_65 = round(n/sum(n)*100, digits=1)) %>%\n  select(-age_range) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 3\n   citizenship     n pct_65\n   <chr>       <int>  <dbl>\n 1 Japan         342   38.7\n 2 USA           110   12.4\n 3 France         69    7.8\n 4 Germany        48    5.4\n 5 UK             48    5.4\n 6 Italy          33    3.7\n 7 Austria        28    3.2\n 8 Spain          28    3.2\n 9 Russia         23    2.6\n10 Switzerland    22    2.5\n```\n:::\n:::\n\n\n<hr />\nOn the other end of the age spectrum, what percentage of climbers 18-24 years of age come from Asian countries? 66% (The table includes only countries where 18-24 year olds make up at least 1% of climbers.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmembers %>%\n  mutate(age_range = case_when(\n    age <= \"17\" ~ \"Under 18\",\n    age >= \"18\" & age <= \"24\" ~ \"18-24\",\n    age >= \"25\" & age <= \"34\" ~ \"25-34\",\n    age >= \"35\" & age <= \"44\" ~ \"35-44\",\n    age >= \"45\" & age <= \"54\" ~ \"45-54\",\n    age >= \"55\" & age <= \"64\" ~ \"55-64\",\n    age >= \"65\" ~ \"65+\",\n    TRUE ~ \"Unknown\")) %>%\n  filter(age_range != \"Unknown\") %>%\n  count(citizenship, age_range, sort=T) %>%\n  filter(age_range == \"18-24\") %>%\n  mutate(pct_1824 = round(n/sum(n)*100)) %>%\n  filter(citizenship %in% c(\"Bangladesh\", \"Bhutan\", \"China\", \"India\", \"Indonesia\", \"Iran\", \"Israel\", \"Japan\", \"Kazakhstan\", \"Kuwait\", \"Malaysia\", \"Nepal\", \"Pakistan\", \"S Korea\", \"Singapore\", \"Taiwan\", \"Uzbekistan\", \"Vietnam\") & pct_1824 >= 1) %>%\n  select(-age_range)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  citizenship     n pct_1824\n  <chr>       <int>    <dbl>\n1 Nepal        1956       34\n2 Japan         761       13\n3 S Korea       388        7\n4 China         378        7\n5 India         231        4\n6 Iran           32        1\n```\n:::\n:::\n\n<hr />\nAre Asian countries indeed the ones with the highest percentages of climbers 18-24 years of age? Yes, China leads the list with 20% of its climbers within the age group, while Slovenia is the only non-Asian country in which the age group makes up a double-digit percentage, at 11%. Countries with trips numbering fewer than 10 have been removed from the list.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmembers %>%\n  mutate(age_range = case_when(\n    age <= \"17\" ~ \"Under 18\",\n    age >= \"18\" & age <= \"24\" ~ \"18-24\",\n    age >= \"25\" & age <= \"34\" ~ \"25-34\",\n    age >= \"35\" & age <= \"44\" ~ \"35-44\",\n    age >= \"45\" & age <= \"54\" ~ \"45-54\",\n    age >= \"55\" & age <= \"64\" ~ \"55-64\",\n    age >= \"65\" ~ \"65+\",\n    TRUE ~ \"Unknown\")) %>%\n  filter(age_range != \"Unknown\") %>%\n  count(citizenship, age_range, sort=T) %>%\n  group_by(citizenship) %>%\n  mutate(pct = round(n/sum(n)*100)) %>%\n  ungroup() %>%\n  filter(age_range == \"18-24\" & n > 9) %>%\n  arrange(desc(pct)) %>%\n  select(-age_range) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 3\n   citizenship     n   pct\n   <chr>       <int> <dbl>\n 1 Indonesia      27    31\n 2 China         378    20\n 3 Malaysia       22    16\n 4 Yugoslavia     75    15\n 5 Nepal        1956    14\n 6 S Korea       388    13\n 7 India         231    13\n 8 Japan         761    12\n 9 Slovenia       64    11\n10 Iran           32    10\n```\n:::\n:::\n\n<hr />\nHow many climbers in the dataset are under 18? Out of 76,519 expeditions, 124 of them were undertaken teenagers, while two are even younger at the age of 7 (Italian, 1984) and 12 (Nepalese, 1984). See the breakdown by age group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmembers %>%\n  mutate(age_range = case_when(\n    age <= 17 ~ \"Under 18\",\n    age >= 18 & age <= \"24\" ~ \"18-24\",\n    age >= 25 & age <= \"34\" ~ \"25-34\",\n    age >= 35 & age <= \"44\" ~ \"35-44\",\n    age >= 45 & age <= \"54\" ~ \"45-54\",\n    age >= 55 & age <= \"64\" ~ \"55-64\",\n    age >= 65 ~ \"65+\",\n    TRUE ~ \"Unknown\")) %>%\n  filter(age_range != \"Unknown\") %>%\n  count(age_range, sort=T) %>%\n  mutate(pct = n/sum(n)*100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 7 × 3\n  age_range     n    pct\n  <chr>     <int>  <dbl>\n1 25-34     27199 37.2  \n2 35-44     22778 31.2  \n3 45-54     11963 16.4  \n4 18-24      5804  7.95 \n5 55-64      4269  5.85 \n6 65+         883  1.21 \n7 Under 18    126  0.173\n```\n:::\n:::\n\n\n### Women Climbers\nThe final visualization looks at the percentage of expeditions taken by women, by country while also giving an overview of the countries (that have had women climbers) represented in the dataset. \n\nThis code sets up a world map base layer using the `rnaturalearth` package. \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rnaturalearth)\n\nworld_map <- ne_countries(scale=\"medium\",\n\t\t\t\t\ttype=\"countries\",\n\t\t\t\t\treturnclass=\"sf\")\n\nggplot() +\n  geom_sf(data=world_map, size=0.25, fill=\"#fafafa\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\nThe following produces a dataframe showing the percentage of expeditions by women, based on country. Only countries with at least 10 women are included. I'll join this subset with the map data.\n\n::: {.cell}\n\n```{.r .cell-code}\nexpeditions_women <- members %>%\n  mutate(sex = ifelse(sex == \"F\", \"Women\", \"Men\")) %>%\n  filter(sex != \"NA\") %>%\n  count(citizenship, sex) %>%\n  group_by(citizenship) %>%\n  mutate(pct = round(n/sum(n)*100)) %>%\n  ungroup() %>%\n  mutate(sex = factor(sex, levels=c(\"Men\", \"Women\"))) %>%\n  filter(sex==\"Women\" & n > 9 & !str_detect(citizenship, \"/\")) # remove dual-country citizenship\n```\n:::\n\n\nNow checking for which country names do not match and thus have to be edited in the `expeditions_women` dataframe, using `setdiff()`. This line asks: What country names in the citizenship column of the subset *are not* in the country names in the map data?\n\n::: {.cell}\n\n```{.r .cell-code}\nsetdiff(expeditions_women$citizenship, world_map$geounit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Czechoslovakia\" \"S Africa\"       \"S Korea\"        \"UK\"            \n[5] \"USA\"            \"W Germany\"      \"Yugoslavia\"    \n```\n:::\n:::\n\n\nBased on the results, I'm removing the country names that no longer exist and renaming the rest.\n\n::: {.cell}\n\n```{.r .cell-code}\nexpeditions_women <- expeditions_women %>%\n  # removing country names that no longer exist\n  filter(!str_detect(citizenship, \"Czechoslovakia|USSR|W Germany|Yugoslavia\")) %>%\n  # renaming countries\n  mutate(citizenship = str_replace_all(\n    citizenship,\n    c(\n      \"Bosnia-Herzegovina\" = \"Bosnia and Herzegovina\",\n      \"S Africa\" = \"South Africa\",\n      \"S Korea\" = \"South Korea\",\n      \"Serbia\" = \"Republic of Serbia\",\n      \"UK\" = \"United Kingdom\",\n      \"USA\" = \"United States of America\"\n    )\n  ))\n\n# check > should have no results\nsetdiff(expeditions_women$citizenship, world_map$geounit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncharacter(0)\n```\n:::\n:::\n\n\nHere is a table of the final 49 countries, sorted by the percentage of expeditions involving women.\n\n::: {.cell}\n\n```{.r .cell-code}\nexpeditions_women %>%\n  arrange(desc(pct)) %>%\n  select(-sex) %>%\n  select(Citizenship=citizenship, `# of expeditions, women`=n, `% of all expeditions`=pct) %>%\n  datatable()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-931a820f5317cb06d778\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-931a820f5317cb06d778\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\"],[\"Kosovo\",\"Guatemala\",\"Croatia\",\"Andorra\",\"Lithuania\",\"Finland\",\"Norway\",\"Brazil\",\"Singapore\",\"Taiwan\",\"France\",\"Mexico\",\"Switzerland\",\"Canada\",\"Sweden\",\"Germany\",\"Hungary\",\"Iran\",\"Poland\",\"Australia\",\"Belgium\",\"China\",\"Indonesia\",\"South Africa\",\"United States of America\",\"India\",\"Netherlands\",\"Austria\",\"Chile\",\"Ecuador\",\"Ireland\",\"Japan\",\"New Zealand\",\"Czech Republic\",\"Denmark\",\"Russia\",\"United Kingdom\",\"Bulgaria\",\"Greece\",\"Italy\",\"Romania\",\"Spain\",\"Kazakhstan\",\"Argentina\",\"Slovenia\",\"Ukraine\",\"South Korea\",\"Slovakia\",\"Nepal\"],[10,10,37,11,15,44,127,32,23,19,744,46,381,171,55,378,21,46,200,191,60,291,12,22,806,247,93,220,20,12,23,639,79,60,18,123,492,19,13,220,15,273,10,14,32,21,147,10,178],[83,71,37,35,28,24,22,19,18,18,16,16,16,15,15,14,14,14,14,13,13,13,13,13,13,12,12,10,10,10,10,10,10,9,9,9,9,8,8,8,8,8,7,6,6,6,5,5,1]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Citizenship<\\/th>\\n      <th># of expeditions, women<\\/th>\\n      <th>% of all expeditions<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[2,3]},{\"orderable\":false,\"targets\":0}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\nWith the exception of Norway, the countries where women make up more than 20% of the expeditions have relatively low numbers, with the number of women under 50. Most of them also happen to be small countries, area-wise, so they are not immediately visible on the map. Instead, you see swaths of yellow with subtle variations, signifying percentages of expeditions with women in the teens or lower.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# join map layer with countries in Himalayan dataset\nexpeditions_women_maplayer <- world_map %>%\n  right_join(expeditions_women, by=c(\"geounit\"=\"citizenship\"))\n\nmap <- ggplot() +\n  geom_sf(data=world_map, size=0.25, color=\"#888888\", fill=\"#f9f9f9\") +\n  geom_sf(data=expeditions_women_maplayer, size=0.25, color=\"#888888\", aes(fill=pct)) +\n  scale_fill_gradient(low = \"#ffff3f\", high = \"#007f5f\") +\n  theme_void() +\n  theme(plot.title = element_text(face=\"bold\"),\n        plot.title.position = \"plot\",\n        legend.position = \"top\", \n        legend.justification = \"center\",\n        legend.direction = \"horizontal\",\n        text = element_text(family = \"Commissioner\"),\n        panel.background = element_rect(fill = \"#fff7f5\", color = NA),\n        legend.spacing.x = unit(0.4, 'cm')) +\n  guides(fill = guide_colorbar(title.vjust = 0.75, barheight = 1)) +\n  labs(fill=\"% of Women\",\n       title=\"Expeditions Undertaken by Women\",\n       subtitle=\"Includes countries with at least 10 expeditions by women\\n\",\n       caption = \"Source: #TidyTuesday | Himalayan Database\")\n\n# completely fill background with specified page color (eliminating white bands as happened when only running the plot)\n# https://gis.stackexchange.com/questions/269224/ggplot2-map-with-colored-background-and-coord-map\ncowplot::ggdraw(map) + \n  theme(plot.background = element_rect(fill=\"#fff7f5\", color = NA))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n:::\n\n\nA larger map would improve the visibility of the smaller countries but given the format constraints of this page, I'll try grouping the percentages and using more distinct colors for the ramp.\n\n::: {.cell}\n\n```{.r .cell-code}\n# range of % values\nexpeditions_women %>%\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n citizenship           sex           n              pct       \n Length:49          Men  : 0   Min.   : 10.0   Min.   : 1.00  \n Class :character   Women:49   1st Qu.: 19.0   1st Qu.: 9.00  \n Mode  :character              Median : 46.0   Median :13.00  \n                               Mean   :137.3   Mean   :15.57  \n                               3rd Qu.:191.0   3rd Qu.:16.00  \n                               Max.   :806.0   Max.   :83.00  \n```\n:::\n:::\n\n\nPercentages run from 1-83 but was is the distribution (in order to know the which percentage groups to make)?\n\n::: {.cell}\n\n```{.r .cell-code}\nexpeditions_women %>%\n  ggplot(aes(x=pct)) +\n    geom_histogram(stat=\"count\", alpha=0.8, fill=\"#333C83\") +\n    scale_y_continuous(expand = c(0, 0)) +\n    theme_him\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in geom_histogram(stat = \"count\", alpha = 0.8, fill = \"#333C83\"):\nIgnoring unknown parameters: `binwidth`, `bins`, and `pad`\n```\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-64-1.png){width=672}\n:::\n:::\n\n\nWith most of the percentages clustered under 20, I'll create the groups as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nexp_women_v2 <- expeditions_women %>%\n  mutate(pct_group = case_when(\n    pct <= 10 ~ \"1-10\",\n    pct > 10 & pct <= 20 ~ \"11-20\",\n    pct > 20 ~ \"More than 20\")) %>%\n  # to set order for colors\n  mutate(pct_group = factor(pct_group, levels=c(\"1-10\", \"11-20\", \"More than 20\")))\n\nexp_women_v2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 49 × 5\n   citizenship sex       n   pct pct_group   \n   <chr>       <fct> <int> <dbl> <fct>       \n 1 Andorra     Women    11    35 More than 20\n 2 Argentina   Women    14     6 1-10        \n 3 Australia   Women   191    13 11-20       \n 4 Austria     Women   220    10 1-10        \n 5 Belgium     Women    60    13 11-20       \n 6 Brazil      Women    32    19 11-20       \n 7 Bulgaria    Women    19     8 1-10        \n 8 Canada      Women   171    15 11-20       \n 9 Chile       Women    20    10 1-10        \n10 China       Women   291    13 11-20       \n# … with 39 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nexp_women_maplayer_v2 <- world_map %>%\n  right_join(exp_women_v2, by=c(\"geounit\"=\"citizenship\"))\n\nmap_v2 <- ggplot() +\n  geom_sf(data=world_map, size=0.25, color=\"#888888\", fill=\"#f9f9f9\") +\n  geom_sf(data=exp_women_maplayer_v2, size=0.15, color=\"#888888\", alpha=0.7, aes(fill=pct_group)) +\n  scale_fill_manual(values=c(\"#fcbf49\", \"#f77f00\", \"#d62828\")) +\n  theme_void() +\n  theme(plot.title = element_text(face=\"bold\"),\n        plot.title.position = \"plot\",\n        legend.position = \"top\", \n        legend.justification = \"left\",\n        legend.direction = \"horizontal\",\n        legend.text = element_text(margin = margin(r=0.25, unit=\"cm\"), size = 10),\n        text = element_text(family = \"Commissioner\"),\n        panel.background = element_rect(fill = \"#fff7f5\", color = NA),\n        legend.box.margin = margin(c(0,0,0,-2))\n        #legend.spacing.x = unit(0.25, 'cm')\n        ) +\n  labs(fill=NULL,\n       title=\"% of Expeditions Undertaken by Women\",\n       subtitle=\"Includes countries with at least 10 expeditions by women\\n\",\n       caption = \"Source: #TidyTuesday | Himalayan Database\")\n\n# completely fill background with specified page color (eliminating white bands as happened when only running the plot)\n# https://gis.stackexchange.com/questions/269224/ggplot2-map-with-colored-background-and-coord-map\ncowplot::ggdraw(map_v2) + \n  theme(plot.background = element_rect(fill=\"#fff7f5\", color = NA))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-68-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/htmlwidgets-1.6.2/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.27/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.12.1/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.12.1/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.12.1/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}